name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        id: ssh_deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NODE_SERVER_HOST }}
          username: ${{ secrets.NODE_SERVER_USERNAME }}
          password: ${{ secrets.NODE_SERVER_PASSWORD  }}
          script: sh deploy.sh